apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  type: LoadBalancer # Change to NodePort or ClusterIP as needed
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
